---
- hosts: localhost
  tasks:

  - name: Fetch Proxy Service
    set_fact:
      proxy_svc: "{{ lookup('kubernetes.core.k8s', kind='Service', label_selector='proxy=mitm')[0] }}"
  - debug:
      var: proxy_svc
  - name: Extract Cluster IP
    set_fact:
      proxy_cluster_ip: "{{ proxy_svc | community.general.json_query('spec.clusterIP') }}"
  - debug:
      var: proxy_cluster_ip
