# permissions for end users to view ansibleproxydemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleproxydemo-viewer-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - ansibleproxydemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - ansibleproxydemoes/status
  verbs:
  - get
