apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
  namespace: default
  labels:
    proxy: mitm
spec:
  containers:
    - name: mitm-proxy
      image: registry-1.docker.io/mitmproxy/mitmproxy
      ports: 
        - name: web
          containerPort: 8080
      command: ["mitmdump"]


