apiVersion: v1
kind: Service
metadata:
  labels:
    proxy: mitm
  name: mitm-proxy
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    proxy: mitm
  type: ClusterIP
